<a href="https://colab.research.google.com/github/LifnaJos/ADC601-Data-Analytics-Visualization/blob/DAV_Colab_Notebooks/Data_Preprocessing_techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Proprocessing Techniques**
*   Numerical Data - Feature Scaling
*   Handling Numerical Data
*   Handling Categorical Data
*   Data Splitting for Training & Testing

*Self Learning Topic : Outlier Detection*

# **Step - 1 : Importing the Libraries**

In [ ]:
# libraries
import numpy as np # used for handling numbers
import pandas as pd # used for handling the dataset
from sklearn.impute import SimpleImputer # used for handling missing data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder # used for encoding categorical data
from sklearn.model_selection import train_test_split # used for splitting training and testing data
from sklearn.preprocessing import StandardScaler # used for feature scaling

# **Step - 2 : Importing the Dataset**
- For the lab session download [dataset from Github](https://github.com/tarunlnmiit/machine_learning/blob/master/DataPreprocessing.csv)

In [ ]:
# It will prompt you to select a file. Click on “Choose Files” then select and upload the file. Wait for the file to be 100% uploaded.

from google.colab import files
uploaded = files.upload()

In [ ]:
# To store dataset in a Pandas Dataframe
import io
df = pd.read_csv(io.BytesIO(uploaded['DataPreprocessing.csv']))

# **Step - 3 : Data Exploration**

In [ ]:
# Dimension of the DataFrame
df.shape

(10, 4)

In [ ]:
# Display the DataFrame
df

Region   Age   Income Online Shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
4     USA  45.0      NaN            Yes
5   India  40.0  69600.0            Yes
6  Brazil   NaN  62400.0             No
7   India  53.0  94800.0            Yes
8     USA  55.0  99600.0             No
9   India  42.0  80400.0            Yes

In [ ]:
# Obtain first or last few rows of the dataset
df.head(5) # returns first '5' rows of the dataframe

Region   Age   Income Online Shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
4     USA  45.0      NaN            Yes

In [ ]:
df.tail(5) # returns last '5' rows of the dataframe

Region   Age   Income Online Shopper
5   India  40.0  69600.0            Yes
6  Brazil   NaN  62400.0             No
7   India  53.0  94800.0            Yes
8     USA  55.0  99600.0             No
9   India  42.0  80400.0            Yes

In [ ]:
df.columns # returns the names of all the columns of the dataframe in descriptive format

Index(['Region', 'Age', 'Income', 'Online Shopper'], dtype='object')

In [ ]:
# Check the datatype of the columns and number of entries in each :
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Region          10 non-null     object 
 1   Age             9 non-null      float64
 2   Income          9 non-null      float64
 3   Online Shopper  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 400.0+ bytes


In [ ]:
# Note : Non-numeric columns are dropped from the statistical summary provided by df.describe().
df.describe()

Age        Income
count  11.000000     11.000000
mean   43.545455  76581.818182
std     6.904544  13263.319206
min    32.000000  57600.000000
25%    41.000000  67200.000000
50%    43.000000  73200.000000
75%    47.000000  83400.000000
max    55.000000  99600.000000

In [ ]:
# To Summarize of the categorical variables by passing only those columns to describe():
categorical = df.dtypes[df.dtypes == "object"].index
df[categorical].describe()

Region Online Shopper
count      10             10
unique      3              2
top     India            Yes
freq        4              5

In [ ]:
# Display the unique values in a specific column
df["Region"].unique()

array(['India', 'Brazil', 'USA'], dtype=object)

# **Step - 4 : Data Preprocessing**
1. **Dropping Duplicates from Dataset**

In [ ]:
# Drop duplicates from Dataset
df.drop_duplicates(inplace=True)
# inplace=True : dataframe object is modified without creating a copy.
# inplace=False : otherwise
df

Region   Age   Income Online Shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
4     USA  45.0      NaN            Yes
5   India  40.0  69600.0            Yes
6  Brazil   NaN  62400.0             No
7   India  53.0  94800.0            Yes
8     USA  55.0  99600.0             No
9   India  42.0  80400.0            Yes

# **Step - 4 : Data Preprocessing**
1. Dropping Duplicates from Dataset
2. **Handling Numerical Data**
> **Handling Missing Data** : The most common idea is to take the mean of the columns.

In [ ]:
missing = np.where(df["Age"].isnull() == True)
missing

(array([6]),)

In [ ]:
df.fillna(df.mean(),inplace= True)

In [ ]:
df

Region        Age        Income Online Shopper
0   India  49.000000  86400.000000             No
1  Brazil  32.000000  57600.000000            Yes
2     USA  35.000000  64800.000000             No
3  Brazil  43.000000  73200.000000             No
4     USA  45.000000  76533.333333            Yes
5   India  40.000000  69600.000000            Yes
6  Brazil  43.777778  62400.000000             No
7   India  53.000000  94800.000000            Yes
8     USA  55.000000  99600.000000             No
9   India  42.000000  80400.000000            Yes

# **Step - 4 : Data Preprocessing**
1. Dropping Duplicates from Dataset
2. **Handling Numerical Data**
> **Feature Scaling** ensures that no single variable will dominate the others

Download [dataset from Kaggle](https://www.kaggle.com/kaggle/sf-salaries)


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Salaries.csv to Salaries (2).csv


In [ ]:
# To store dataset in a Pandas Dataframe
import io
df_fs = pd.read_csv(io.BytesIO(uploaded['Salaries.csv']))
df_fs.shape

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (3,4,5,6,12) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


(148654, 13)

In [ ]:
df_fs

Id       EmployeeName  ...         Agency Status
0            1     NATHANIEL FORD  ...  San Francisco    NaN
1            2       GARY JIMENEZ  ...  San Francisco    NaN
2            3     ALBERT PARDINI  ...  San Francisco    NaN
3            4  CHRISTOPHER CHONG  ...  San Francisco    NaN
4            5    PATRICK GARDNER  ...  San Francisco    NaN
...        ...                ...  ...            ...    ...
148649  148650      Roy I Tillery  ...  San Francisco     PT
148650  148651       Not provided  ...  San Francisco    NaN
148651  148652       Not provided  ...  San Francisco    NaN
148652  148653       Not provided  ...  San Francisco    NaN
148653  148654          Joe Lopez  ...  San Francisco     PT

[148654 rows x 13 columns]

In [ ]:
# Describe of each numeric column
df_fs.describe()

Id       TotalPay  TotalPayBenefits           Year  Notes
count  148654.000000  148654.000000     148654.000000  148654.000000    0.0
mean    74327.500000   74768.321972      93692.554811    2012.522643    NaN
std     42912.857795   50517.005274      62793.533483       1.117538    NaN
min         1.000000    -618.130000       -618.130000    2011.000000    NaN
25%     37164.250000   36168.995000      44065.650000    2012.000000    NaN
50%     74327.500000   71426.610000      92404.090000    2013.000000    NaN
75%    111490.750000  105839.135000     132876.450000    2014.000000    NaN
max    148654.000000  567595.430000     567595.430000    2014.000000    NaN

In [ ]:
# 1. Rescaling(Min-Max Normalization)
## -- simplest type of normalization where the features are rescaled to the range [0, 1]

# Min Max Normalization using MinMaxScaler in sklearn library
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
TotalPayReshaped = df_fs.TotalPay.values.reshape(-1,1)
df_fs.TotalPay = scaler.fit_transform(TotalPayReshaped)

# minimum value of TotalPay is 0 and the maximum is 1.
df_fs.describe()

Id       TotalPay  TotalPayBenefits           Year  Notes
count  148654.000000  148654.000000     148654.000000  148654.000000    0.0
mean    74327.500000       0.132673      93692.554811    2012.522643    NaN
std     42912.857795       0.088905      62793.533483       1.117538    NaN
min         1.000000       0.000000       -618.130000    2011.000000    NaN
25%     37164.250000       0.064742      44065.650000    2012.000000    NaN
50%     74327.500000       0.126792      92404.090000    2013.000000    NaN
75%    111490.750000       0.187354     132876.450000    2014.000000    NaN
max    148654.000000       1.000000     567595.430000    2014.000000    NaN

In [ ]:
# 2. Standardization (Z-score normalization)
## -- Here feature is scaled such that it’s mean is zero and variance is one.

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

TotalPayReshaped = df_fs.TotalPay.values.reshape(-1,1)
df_fs.TotalPay = scaler.fit_transform(TotalPayReshaped)

# Here mean of TotalPay is close to 0 and the standard deviation is 1.
df_fs.describe()

Id      TotalPay  TotalPayBenefits           Year  Notes
count  148654.000000  1.486540e+05     148654.000000  148654.000000    0.0
mean    74327.500000 -2.573915e-15      93692.554811    2012.522643    NaN
std     42912.857795  1.000003e+00      62793.533483       1.117538    NaN
min         1.000000 -1.492304e+00       -618.130000    2011.000000    NaN
25%     37164.250000 -7.640884e-01      44065.650000    2012.000000    NaN
50%     74327.500000 -6.615046e-02      92404.090000    2013.000000    NaN
75%    111490.750000  6.150586e-01     132876.450000    2014.000000    NaN
max    148654.000000  9.755700e+00     567595.430000    2014.000000    NaN

# **Step - 4 : Data Preprocessing**
1. Dropping Duplicates from Dataset
2. Handling Numerical Data
3. **Handling of Categorical Data**
> Label Encoding & One Hot Encoding



In [ ]:
df

Region        Age        Income Online Shopper
0   India  49.000000  86400.000000             No
1  Brazil  32.000000  57600.000000            Yes
2     USA  35.000000  64800.000000             No
3  Brazil  43.000000  73200.000000             No
4     USA  45.000000  76533.333333            Yes
5   India  40.000000  69600.000000            Yes
6  Brazil  43.777778  62400.000000             No
7   India  53.000000  94800.000000            Yes
8     USA  55.000000  99600.000000             No
9   India  42.000000  80400.000000            Yes

In [ ]:
# encode categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

# OnlineShopper Column
le = LabelEncoder()
df['Online Shopper'] = le.fit_transform(df['Online Shopper'] )
df

Region        Age        Income  Online Shopper
0   India  49.000000  86400.000000               0
1  Brazil  32.000000  57600.000000               1
2     USA  35.000000  64800.000000               0
3  Brazil  43.000000  73200.000000               0
4     USA  45.000000  76533.333333               1
5   India  40.000000  69600.000000               1
6  Brazil  43.777778  62400.000000               0
7   India  53.000000  94800.000000               1
8     USA  55.000000  99600.000000               0
9   India  42.000000  80400.000000               1

In [ ]:
onehotencoder = OneHotEncoder()
#reshape the 1-D country array to 2-D as fit_transform expects 2-D and finally fit the object
X = onehotencoder.fit_transform(df.Region.values.reshape(-1,1)).toarray()
X

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [ ]:
# counting unique places in Region
n = len(pd.unique(df['Region']))
n

3

In [ ]:
#To add this back into the original dataframe
dfOneHot = pd.DataFrame(X, columns = ["Region_"+str(int(i)) for i in range(n)])
dfOneHot

Region_0  Region_1  Region_2
0       0.0       1.0       0.0
1       1.0       0.0       0.0
2       0.0       0.0       1.0
3       1.0       0.0       0.0
4       0.0       0.0       1.0
5       0.0       1.0       0.0
6       1.0       0.0       0.0
7       0.0       1.0       0.0
8       0.0       0.0       1.0
9       0.0       1.0       0.0

In [ ]:
#Concatenate the two dataframes
df = pd.concat([dfOneHot, df], axis=1)

In [ ]:
#droping the country column
df= df.drop(['Region'], axis=1)
df

Region_0  Region_1  Region_2        Age        Income  Online Shopper
0       0.0       1.0       0.0  49.000000  86400.000000               0
1       1.0       0.0       0.0  32.000000  57600.000000               1
2       0.0       0.0       1.0  35.000000  64800.000000               0
3       1.0       0.0       0.0  43.000000  73200.000000               0
4       0.0       0.0       1.0  45.000000  76533.333333               1
5       0.0       1.0       0.0  40.000000  69600.000000               1
6       1.0       0.0       0.0  43.777778  62400.000000               0
7       0.0       1.0       0.0  53.000000  94800.000000               1
8       0.0       0.0       1.0  55.000000  99600.000000               0
9       0.0       1.0       0.0  42.000000  80400.000000               1

# **Step - 4 : Data Preprocessing**
1. Dropping Duplicates from Dataset
2. Handling Numerical Data
3. Handling of Categorical Data
4. **Handling Text Data**
> Text normalization techniques



In [ ]:
# Convert text to lowercase
input_str = 'The 5 biggest countries by population in 2017 are China, India, United States, Indonesia, and Brazil.'
input_str = input_str.lower()
print(input_str)

the 5 biggest countries by population in 2017 are china, india, united states, indonesia, and brazil.


In [ ]:
# Remove numbers if they are not relevant to your analyses.
# Usually, regular expressions are used to remove numbers.
import re
input_str = 'Box A contains 3 red and 5 white balls, while Box B contains 4 red and 2 blue balls.'
result = re.sub(r'\d+', '', input_str)
print(result)

Box A contains  red and  white balls, while Box B contains  red and  blue balls.


In [ ]:
# Remove punctuation:  [!”#$%&’()*+,-./:;<=>?@[\]^_`{|}~]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

inp_str = input("Enter a string: ")

no_punc = ""
for char in inp_str:
   if char not in punctuations:
       no_punc = no_punc + char

print("Punctuation Free String: ",no_punc)

Enter a string: This &is [an] example? {of} string. with.? punctuation!!!!
Punctuation Free String:  This is an example of string with punctuation


In [ ]:
# Remove whitespaces
# To remove leading and ending spaces, you can use the strip() function
input_str = ' \t a string example\t '
input_str = input_str.strip()
input_str

'a string example'

In [ ]:
# Remove stop words
!pip install -q wordcloud
import wordcloud

import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

import pandas as pd
import matplotlib.pyplot as plt
import io
import unicodedata
import numpy as np
import re
import string

In [ ]:
example_sent = """This is a sample sentence,
                  showing off the stop words filtration."""

stop_words = set(stopwords.words('english'))

word_tokens = word_tokenize(example_sent)

filtered_sentence = [w for w in word_tokens if not w.lower() in stop_words]

filtered_sentence = []

for w in word_tokens:
    if w not in stop_words:
        filtered_sentence.append(w)

print(word_tokens)
print(filtered_sentence)

['This', 'is', 'a', 'sample', 'sentence', ',', 'showing', 'off', 'the', 'stop', 'words', 'filtration', '.']
['This', 'sample', 'sentence', ',', 'showing', 'stop', 'words', 'filtration', '.']


In [ ]:
# Stemming using NLTK
# Stemming : process of reducing words to their word stem, base or root form
# (for example, books — book, looked — look).

stemmer = nltk.stem.PorterStemmer()
input_str= 'There are several types of stemming algorithms.'
input_str=word_tokenize(input_str)
for word in input_str:
    print(stemmer.stem(word))

there
are
sever
type
of
stem
algorithm
.


In [ ]:
# Lemmatization
# to reduce inflectional forms to a common base form.
# As opposed to stemming, lemmatization does not simply chop off inflections.
# Instead it uses lexical knowledge bases to get the correct base forms of words.
lemmatizer = nltk.stem.WordNetLemmatizer()
input_str='been had done languages cities mice'
input_str=word_tokenize(input_str)
for word in input_str:
    print(lemmatizer.lemmatize(word))

been
had
done
language
city
mouse


In [ ]:
# Part of Speech Tagging

input_str= 'Parts of speech examples: an article, to write, interesting, easily, and, of'
from textblob import TextBlob
result = TextBlob(input_str)
print(result.tags)

[('Parts', 'NNS'), ('of', 'IN'), ('speech', 'NN'), ('examples', 'NNS'), ('an', 'DT'), ('article', 'NN'), ('to', 'TO'), ('write', 'VB'), ('interesting', 'VBG'), ('easily', 'RB'), ('and', 'CC'), ('of', 'IN')]


# **Step - 4 : Data Preprocessing**
1. Dropping Duplicates from Dataset
2. Handling Numerical Data
3. Handling of Categorical Data
4. Handling Text Data
5. **Data Splitting for Training & Testing**



In [ ]:
df

Region_0  Region_1  Region_2        Age        Income  Online Shopper
0       0.0       1.0       0.0  49.000000  86400.000000               0
1       1.0       0.0       0.0  32.000000  57600.000000               1
2       0.0       0.0       1.0  35.000000  64800.000000               0
3       1.0       0.0       0.0  43.000000  73200.000000               0
4       0.0       0.0       1.0  45.000000  76533.333333               1
5       0.0       1.0       0.0  40.000000  69600.000000               1
6       1.0       0.0       0.0  43.777778  62400.000000               0
7       0.0       1.0       0.0  53.000000  94800.000000               1
8       0.0       0.0       1.0  55.000000  99600.000000               0
9       0.0       1.0       0.0  42.000000  80400.000000               1

In [ ]:
# Splitting the attributes into independent and dependent attributes
X = df.iloc[:, :-1].values # dependent variables
Y = df.iloc[:, -1].values # Class

In [ ]:
X

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.90000000e+01,
        8.64000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.20000000e+01,
        5.76000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.50000000e+01,
        6.48000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.30000000e+01,
        7.32000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 4.50000000e+01,
        7.65333333e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.96000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.37777778e+01,
        6.24000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.30000000e+01,
        9.48000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 5.50000000e+01,
        9.96000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.20000000e+01,
        8.04000000e+04]])

In [ ]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
# splitting the dataset into training set and test set in the ratio 80:20
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [ ]:
X_train

array([[0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 4.50000000e+01,
        7.65333333e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.20000000e+01,
        8.04000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.20000000e+01,
        5.76000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.37777778e+01,
        6.24000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.30000000e+01,
        9.48000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.30000000e+01,
        7.32000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.90000000e+01,
        8.64000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.96000000e+04]])

In [ ]:
X_test

array([[0.00e+00, 0.00e+00, 1.00e+00, 3.50e+01, 6.48e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.50e+01, 9.96e+04]])

In [ ]:
Y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [ ]:
Y_test

array([0, 0])

## **Online References**
***Courtesy to the following Online Sources***
1. https://towardsdatascience.com/data-preprocessing-in-data-mining-machine-learning-79a9662e2eb  
2. https://towardsdatascience.com/data-preprocessing-in-python-b52b652e37d5
2.   https://towardsdatascience.com/data-pre-processing-a-step-by-step-guide-541b083912b5
3. https://www.kdnuggets.com/2020/07/easy-guide-data-preprocessing-python.html
4. https://www.section.io/engineering-education/data-preprocessing-python/
5. https://data-flair.training/blogs/python-ml-data-preprocessing/
6. https://viso.ai/deep-learning/data-preprocessing-techniques-for-machine-learning-with-python/
7. https://www.upgrad.com/blog/data-preprocessing-in-machine-learning/
8. https://www.analyticsvidhya.com/blog/2016/07/practical-guide-data-preprocessing-python-scikit-learn/
9. https://www.tutorialspoint.com/machine_learning_with_python/machine_learning_with_python_data_preprocessing_analysis_visualization.htm
10. https://www.geeksforgeeks.org/data-preprocessing-machine-learning-python/
11. https://medium.com/@suneet.bhopal/data-preprocessing-using-python-1bfee9268fb3
12. https://www.analyticsvidhya.com/blog/2020/03/one-hot-encoding-vs-label-encoding-using-scikit-learn/
13. https://www.kaggle.com/hamelg/python-for-data-16-preparing-numeric-data

